spring:
  profiles:
    active: dev
  application:
    name: crypto-market-ai-chatbot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
server:
  port: 4242

gemini:
    api:
        key: ${GEMINI_API_KEY}
